### ISSUE TITLE
Probezeit in Embed intigrieren

### ISSUE THREAD

**Issue by Fabi8killer** [M1chelle99/DiscordManager#14]
1. User schickt Bewerbung ab
2. Taucht in Text Channel bei den Managern auf
3. Nun steht stehen zwei Emojis zur Verfügung:
Probezeit 4 Wochen und Probezeit 6 Wochen
4. Manager wählt eins aus -> Wird in Embed und Datenbank ergänzt
5. Nun tauchen wieder die alt bekannten Emojis auf:
:white_check_mark:  und  :x: 
6. Bot erkennt sobald die Probezeit vorbei ist und schickt diese Embed an einen speziellen Text-Channel.
7. Dort sind wieder unter der Embed die zwei Emojis:
:white_check_mark:  und  :x: 

Falls das nicht geht einfach bescheid geben. Oder vielleicht findest ja auch noch eine andere Lösung ;)

**Comment by mysticalfoxie** [comment]
Wrong Project 😉
